name: ci

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
    tags: ["*"]

permissions:
  contents: read

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.23.2'

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v6.0.0
      with:
        version: latest
        skip-cache: true

    - name: Run Go tests
      run: go test -v -race ./...
